dist: xenial
sudo: required
language: c

git:
  depth: 1
  quiet: true
  submodules: false

branches:
  only:
    master

before_install:
  - git submodule update --init

addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - cmake
      - ninja-build
      - make
      - binutils
      - clang++-7
      - clang-7
      - curl

install:
  - curl -SOL https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2
  - tar xjf gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2
  - sudo cp -r ./gcc-arm-none-eabi-7-2018-q2-update/* /usr/local/
  - curl -SOL https://github.com/danmar/cppcheck/archive/1.85.tar.gz
  - tar xzf 1.85.tar.gz
  - (cd cppcheck-1.85 && make CXX=`which clang++-7` SRCDIR=build CFGDIR=/usr/share/cppcheck/ HAVE_RULES=yes CXXFLAGS="-O2 -DNDEBUG -Wall -Wno-sign-compare -Wno-unused-function" -j2 && make install CFGDIR=/usr/share/cppcheck/)

script:
  - ./ci/scripts/test-cppcheck.sh
  - ./ci/scripts/build-gcc.sh
