dist: xenial
sudo: required
language: c

git:
  depth: 1
  quiet: true
  submodules: false

branches:
  only:
    master

cache:
  timeout: 1000
  directories:
    - ${HOME}/.cache

addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - cmake
      - ninja-build
      - make
      - binutils
      - clang++-7
      - clang-7
      - curl

install:
  - ./ci/scripts/install-cppcheck.sh
  - ./ci/scripts/install-gcc-toolchain.sh
  - git submodule update --init

script:
  - ./ci/scripts/test-cppcheck.sh
  - ./ci/scripts/build-gcc.sh
