dist: xenial
sudo: required
language: c

git:
  depth: 1
  quiet: true
  submodules: false

branches:
  only:
    master

before_install:
  - git submodule update --init

addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - cmake
      - ninja-build
      - make
      - binutils
      - clang++-7
      - clang-7
      - curl
    snaps:
      - cppcheck

install:
  - curl -SOL https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2
  - tar xjf gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2
  - sudo cp -r ./gcc-arm-none-eabi-7-2018-q2-update/* /usr/local/

script:
  - ./ci/scripts/test-cppcheck.sh
  - ./ci/scripts/build-gcc.sh
