image: Ubuntu

branches:
  only:
  - master

platform: x64
configuration: Release
stack: node 12

cache:
  - ${HOME}/opt/xPacks

install:
  - git submodule init
  - git submodule update --init --recursive
  - sh: npm install --global xpm
  - sh: xpm install --global @xpack-dev-tools/arm-none-eabi-gcc@9.2.1-1.1.1
  - sh: sudo apt-get update
  - sh: sudo apt-get install -y --fix-missing cmake ninja-build

build_script:
  - sh: |
        export PATH="${HOME}/opt/xPacks/@xpack-dev-tools/arm-none-eabi-gcc/9.2.1-1.1.1/.content/bin:${PATH}"
        mkdir build && cd build
        cmake -DSTG_MODEL:STRING=856 -DCMAKE_TOOLCHAIN_FILE=arm-gcc-toolchain.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -GNinja ..
        cmake --build .