image: Ubuntu1804

platform: x64
configuration: Release
stack: node 10

cache:
  - ${HOME}/opt/xPacks

install:
  - git submodule init
  - git submodule update
  - sh: npm install --global xpm
  - sh: xpm install --global @gnu-mcu-eclipse/arm-none-eabi-gcc@7.3.1-1.1.1
  - sh: sudo apt-get install -y cmake ninja-build

build_script:
  - sh: |
        export PATH="${HOME}/opt/xPacks/@gnu-mcu-eclipse/arm-none-eabi-gcc/7.3.1-1.1.1/.content/bin:${PATH}"
        mkdir build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=arm-gcc-toolchain.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -GNinja ..
        cmake --build .