//$file${.::uavcan_node::uavcan_node_ao_private.h} vvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: app.qm
// File:  ${.::uavcan_node::uavcan_node_ao_private.h}
//
// This code has been generated by QM 5.3.0 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::uavcan_node::uavcan_node_ao_private.h} ^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef _UAVCAN_NODE_AO_PRIVATE_H
#define _UAVCAN_NODE_AO_PRIVATE_H

#include "app.h"

enum UavcanNodeSignals {
  RESTART_SIG = APP_UAVCAN_RESTART_SIG,
  SPIN_TIMEOUT_SIG = APP_UAVCAN_SPIN_TIMEOUT_SIG,
  STATUS_TIMEOUT_SIG = APP_UAVCAN_STATUS_TIMEOUT_SIG
};

#define UAVCAN_NODE_SPIN_TIMEOUT (BSP_TICKS_PER_MS * APP_UAVCAN_NODE_SPIN_PERIOD_MS)
#define UAVCAN_NODE_STATUS_TIMEOUT (BSP_TICKS_PER_MS * APP_UAVCAN_NODE_STATUS_PERIOD_MS)

#endif /* _UAVCAN_NODE_AO_PRIVATE_H */
