//$file${.::uavcan_node::uavcan_node_ao.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: app.qm
// File:  ${.::uavcan_node::uavcan_node_ao.c}
//
// This code has been generated by QM 5.3.0 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::uavcan_node::uavcan_node_ao.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"    /* QP/C framework API */
#include "bsp_qpc.h" /* Board Support Package interface */
#include "uavcan_node_ao.h"

/* Declarations */
//$declare${AOs::UavcanNode_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::UavcanNode_ctor} ....................................................
static void UavcanNode_ctor(void);
//$enddecl${AOs::UavcanNode_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::UavcanNode} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::UavcanNode} .........................................................
typedef struct {
// protected:
    QMActive super;

// private:
    QTimeEvt spinTimeEvt;
    QTimeEvt statusTimeEvt;
    uint_fast8_t wasHardwareInitialized;
} UavcanNode;

// protected:
static QState UavcanNode_initial(UavcanNode * const me, void const * const par);
static QState UavcanNode_hardwareInit  (UavcanNode * const me, QEvt const * const e);
static QState UavcanNode_hardwareInit_e(UavcanNode * const me);
static QState UavcanNode_hardwareInit_x(UavcanNode * const me);
static QMState const UavcanNode_hardwareInit_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&UavcanNode_hardwareInit),
    Q_ACTION_CAST(&UavcanNode_hardwareInit_e),
    Q_ACTION_CAST(&UavcanNode_hardwareInit_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState UavcanNode_online  (UavcanNode * const me, QEvt const * const e);
static QState UavcanNode_online_e(UavcanNode * const me);
static QState UavcanNode_online_x(UavcanNode * const me);
static QMState const UavcanNode_online_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&UavcanNode_online),
    Q_ACTION_CAST(&UavcanNode_online_e),
    Q_ACTION_CAST(&UavcanNode_online_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState UavcanNode_aboutToRestart  (UavcanNode * const me, QEvt const * const e);
static QState UavcanNode_aboutToRestart_e(UavcanNode * const me);
static QMState const UavcanNode_aboutToRestart_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&UavcanNode_aboutToRestart),
    Q_ACTION_CAST(&UavcanNode_aboutToRestart_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//$enddecl${AOs::UavcanNode} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/* Instances */
static UavcanNode l_uavcanNode;
QMActive * const AO_uavcanNode = &l_uavcanNode.super;

/* Definitions */
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::UavcanNode_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::UavcanNode_ctor} ....................................................
static void UavcanNode_ctor(void) {
    UavcanNode *me = (UavcanNode *)AO_uavcanNode;
    QMActive_ctor(&me->super, Q_STATE_CAST(&UavcanNode_initial));
    QTimeEvt_ctorX(&me->spinTimeEvt, &me->super.super, SPIN_TIMEOUT_SIG, 0U);
    QTimeEvt_ctorX(&me->statusTimeEvt, &me->super.super, STATUS_TIMEOUT_SIG, 0U);
}
//$enddef${AOs::UavcanNode_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::UavcanNode} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::UavcanNode} .........................................................

//${AOs::UavcanNode::SM} .....................................................
static QState UavcanNode_initial(UavcanNode * const me, void const * const par) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &UavcanNode_hardwareInit_s, // target state
        {
            Q_ACTION_CAST(&UavcanNode_hardwareInit_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    //${AOs::UavcanNode::SM::initial}
    (void)par; /* unused parameter */

    QActive* parent = &me->super.super;

    QActive_subscribe(parent, RESTART_SIG);
    return QM_TRAN_INIT(&tatbl_);
}

//${AOs::UavcanNode::SM::hardwareInit} .......................................
//${AOs::UavcanNode::SM::hardwareInit}
static QState UavcanNode_hardwareInit_e(UavcanNode * const me) {
    // retry every 500 ms
    QTimeEvt_armX(&me->spinTimeEvt, BSP_TICKS_PER_MS * 5U, BSP_TICKS_PER_MS * 500U);
    return QM_ENTRY(&UavcanNode_hardwareInit_s);
}
//${AOs::UavcanNode::SM::hardwareInit}
static QState UavcanNode_hardwareInit_x(UavcanNode * const me) {
    QTimeEvt_disarm(&me->spinTimeEvt);
    return QM_EXIT(&UavcanNode_hardwareInit_s);
}
//${AOs::UavcanNode::SM::hardwareInit}
static QState UavcanNode_hardwareInit(UavcanNode * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::UavcanNode::SM::hardwareInit::SPIN_TIMEOUT}
        case SPIN_TIMEOUT_SIG: {
            me->wasHardwareInitialized = BSP_CAN_init(BSP_CAN_getFilterConfig());
            //${AOs::UavcanNode::SM::hardwareInit::SPIN_TIMEOUT::[me->wasHardwareInitialized]}
            if (me->wasHardwareInitialized) {
                static struct {
                    QMState const *target;
                    QActionHandler act[3];
                } const tatbl_ = { // tran-action table
                    &UavcanNode_online_s, // target state
                    {
                        Q_ACTION_CAST(&UavcanNode_hardwareInit_x), // exit
                        Q_ACTION_CAST(&UavcanNode_online_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                initCanardInstance();
                status_ = QM_TRAN(&tatbl_);
            }
            //${AOs::UavcanNode::SM::hardwareInit::SPIN_TIMEOUT::[else]}
            else {
                status_ = QM_HANDLED();
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${AOs::UavcanNode::SM::online} .............................................
//${AOs::UavcanNode::SM::online}
static QState UavcanNode_online_e(UavcanNode * const me) {
    // Spin every 25 ms
    QTimeEvt_armX(&me->spinTimeEvt, BSP_TICKS_PER_MS * 25U, BSP_TICKS_PER_MS * 25U);
    // Send status every 450 ms
    QTimeEvt_armX(&me->statusTimeEvt, BSP_TICKS_PER_MS * 450U, BSP_TICKS_PER_MS * 450U);

    return QM_ENTRY(&UavcanNode_online_s);
}
//${AOs::UavcanNode::SM::online}
static QState UavcanNode_online_x(UavcanNode * const me) {
    QTimeEvt_disarm(&me->spinTimeEvt);
    QTimeEvt_disarm(&me->statusTimeEvt);
    return QM_EXIT(&UavcanNode_online_s);
}
//${AOs::UavcanNode::SM::online}
static QState UavcanNode_online(UavcanNode * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::UavcanNode::SM::online::SPIN_TIMEOUT}
        case SPIN_TIMEOUT_SIG: {
            receiveAll();
            sendAll();
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::UavcanNode::SM::online::STATUS_TIMEOUT}
        case STATUS_TIMEOUT_SIG: {
            statusUpdate();
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::UavcanNode::SM::online::RESTART}
        case RESTART_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { // tran-action table
                &UavcanNode_aboutToRestart_s, // target state
                {
                    Q_ACTION_CAST(&UavcanNode_online_x), // exit
                    Q_ACTION_CAST(&UavcanNode_aboutToRestart_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${AOs::UavcanNode::SM::aboutToRestart} .....................................
//${AOs::UavcanNode::SM::aboutToRestart}
static QState UavcanNode_aboutToRestart_e(UavcanNode * const me) {
    BSP_restart();
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&UavcanNode_aboutToRestart_s);
}
//${AOs::UavcanNode::SM::aboutToRestart}
static QState UavcanNode_aboutToRestart(UavcanNode * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}
//$enddef${AOs::UavcanNode} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
