//$file${.::uavcan_node::uavcan_node_ao.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: app.qm
// File:  ${.::uavcan_node::uavcan_node_ao.h}
//
// This code has been generated by QM 5.3.0 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::uavcan_node::uavcan_node_ao.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef _UAVCAN_NODE_AO_H
#define _UAVCAN_NODE_AO_H

#include "qpc.h"
#include "canard.h"

extern QActive * AO_uavcanNode;

void UavcanNode_ctor(QActive * ao);

CanardInstance * getCanardInstance(void);

#endif /* _UAVCAN_NODE_AO_H */
